#!/usr/bin/env bash
set -euxo pipefail

sudo apt-get -y update
sudo apt-get -y upgrade

if [ -z "${CI:-}" ]; then
    sudo apt-get -y install wslu
    wslsys | grep WSL2 || {
        echo "This script is made for Ubuntu on WSL2. However, you seem to be using WSL1.";
        echo "Press enter to continue anyway.";
        read -r;
    };
fi

export XDG_CONFIG_HOME="$HOME/.config"
export DOTFILES_ROOT="$HOME/.dotfiles"

git clone -b "${GITHUB_REF_NAME:-"master"}" https://github.com/ho-oto/dotfiles-for-wsl2 "$DOTFILES_ROOT"
cd "$DOTFILES_ROOT"

script/brew
eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

script/fisher
script/misc

script/dot

if [ -z "${CI:-}" ]; then
    script/cuda
    cp windows/* "$(wslpath "$(wslvar USERPROFILE)")"
fi

echo "Set start_wsl_sshd.bat to Task Scheduler of windows"
