format = "$username$env_var$hostname$all"

[directory]
fish_style_pwd_dir_length = 2
truncation_length = 8

[env_var.WEZTERM_UNIX_SOCKET]
format = "🪢"

[username]
show_always = true

[hostname]
ssh_only = false

[shell]
bash_indicator = "bash "
disabled = false
fish_indicator = ""
format = "[$indicator]($style)"
zsh_indicator = "zsh "
