format = "$username$env_var$hostname$all"

[directory]
truncation_length = 8
fish_style_pwd_dir_length = 2

[env_var.WEZTERM_UNIX_SOCKET]
format = "🪢"

[username]
show_always = true

[hostname]
ssh_only = false

[shell]
disabled = false
bash_indicator = "bash "
fish_indicator = ""
zsh_indicator = "zsh "
format = "[$indicator]($style)"
