# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

if [[ "$(ps -p $PPID -o comm=)" == "sshd" && -z "$VSCODE_IPC_HOOK_CLI" ]]; then
  exec fish --features qmark-noglob
fi

# history
HISTSIZE=1000
HISTFILESIZE=2000
HISTCONTROL=ignoreboth
shopt -s histappend

# alias
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
fi

alias ls='eza --icons --group-directories-first --color=auto'
alias ll='ls --long --header --git'
alias la='ll --all'
alias lt='ls --tree'

alias grep='grep --color=auto'
alias ncdu='ncdu --color dark -rr'

alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'

alias em='emacs'
alias lg='lazygit'

# alias pbcopy='socat - UNIX-CLIENT:$HOME/.clipper.sock'

# completion
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

eval "$(starship init bash)"
eval "$(zoxide init bash)"
