#!/bin/bash

for REPOSITORY in $(sed 's/#.*//' "$DOTFILES_HOME/list/repository" | sed '/^$/d'); do
    sudo add-apt-repository -y "$REPOSITORY"
done
sudo apt -y update
sudo apt -y upgrade
sed 's/#.*//' "$DOTFILES_HOME/list/apt" | sed '/^$/d' | xargs sudo apt -y install
