#!/bin/bash

sed 's/#.*//' "$DOTFILES_HOME/list/repository" | sed '/^$/d' | while IFS= read -r REPOSITORY
do
    sudo add-apt-repository -y "$REPOSITORY"
done

sudo apt -y update
sudo apt -y upgrade
sed 's/#.*//' "$DOTFILES_HOME/list/apt" | sed '/^$/d' | xargs sudo apt -y install
