#!/usr/bin/env bash
set -euxo pipefail

# REPOSITORIES=(
#     ppa:fish-shell/release-3
# )
# echo "${REPOSITORIES[@]}" | xargs -n 1 sudo add-apt-repository -y

PACKAGES=(
    openssh-server
    net-tools
    build-essential
    pkg-config
    m4
    cmake
    gfortran
    procps
    file
    unar
    libssl-dev
    zlib1g-dev
    libffi-dev
    libreadline-dev
    libsqlite3-dev
    libbz2-dev
)

sudo apt-get -y update
sudo apt-get -y upgrade

echo "${PACKAGES[@]}" | xargs sudo apt-get -y install
