#!/bin/bash

if [ -z "$XDG_CONFIG_HOME" ]; then
    XDG_CONFIG_HOME="$HOME/.config"
fi

if [ -z "$DOTFILES_HOME" ]; then
    if [ -f "$HOME/.envdotfiles" ]; then
        DOTFILES_HOME=$(cat "$HOME/.envdotfiles")
    else
        echo "DOTFILES_HOME is unset or empty" >&2 && exit 1
    fi
fi

DOTFILES_CONFIG="$DOTFILES_HOME/.config"

dirshome=(
    .julia/config
    .jupyter
    .config
)
fileshome=(
    .bashrc
    .emacs.el
    .profile
    .tmux.conf
    .julia/config/startup.jl
    .jupyter/jupyter_notebook_config.py
    .config/starship.toml # location of starship.toml is hard-coded as $HOME/.config, not $XDG_CONFIG_HOME
)

dirsxdgc=(
    fish
    git
    broot
)
filesxdgc=(
    fish/config.fish
    # fish/fish_plugins
    git/config
    git/ignore
    broot/conf.toml
)

mkdir -p "$XDG_CONFIG_HOME"

for DIR in "${dirshome[@]}"; do
    mkdir -p "$HOME/$DIR"
done
for FILE in "${fileshome[@]}"; do
    rm -f "$HOME/$FILE"
    ln -s "$DOTFILES_HOME/$FILE" "$HOME/$FILE"
done

for DIR in "${dirsxdgc[@]}"; do
    mkdir -p "$XDG_CONFIG_HOME/$DIR"
done
for FILE in "${filesxdgc[@]}"; do
    rm -f "$XDG_CONFIG_HOME/$FILE"
    ln -s "$DOTFILES_CONFIG/$FILE" "$XDG_CONFIG_HOME/$FILE"
done
