#!/usr/bin/env bash
set -euxo

[ -z "${XDG_CONFIG_HOME:-}" ] && XDG_CONFIG_HOME="$HOME/.config"

dirshome=(
    .julia/config
    .jupyter
    .config
)
fileshome=(
    .hushlogin
    .bashrc
    .emacs.el
    .profile
    .tmux.conf
    .julia/config/startup.jl
    .jupyter/jupyter_notebook_config.py
    .config/starship.toml # location of starship.toml is hard-coded as $HOME/.config, not $XDG_CONFIG_HOME
)

dirsxdgc=(
    fish
    git
    broot
    nano
    pypoetry
)
filesxdgc=(
    fish/config.fish
    git/config
    git/ignore
    broot/conf.toml
    nano/nanorc
    pypoetry/config.toml
)

mkdir -p "$XDG_CONFIG_HOME"

for DIR in "${dirshome[@]}"; do
    mkdir -p "$HOME/$DIR"
done
for FILE in "${fileshome[@]}"; do
    rm -f "$HOME/$FILE"
    ln -s "$DOTFILES_ROOT/config/$FILE" "$HOME/$FILE"
done

for DIR in "${dirsxdgc[@]}"; do
    mkdir -p "$XDG_CONFIG_HOME/$DIR"
done
for FILE in "${filesxdgc[@]}"; do
    rm -f "$XDG_CONFIG_HOME/$FILE"
    ln -s "$DOTFILES_ROOT/config/.config/$FILE" "$XDG_CONFIG_HOME/$FILE"
done
