#!/usr/bin/env bash
set -euxo pipefail

# Rust
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --no-modify-path

# SSH server
sudo apt-get -y install openssh-server
sudo mkdir -p /etc/ssh/sshd_config.d
sudo sh -c "echo 'StreamLocalBindUnlink yes' >> /etc/ssh/sshd_config.d/clipper.conf"
sudo sh -c "echo 'AcceptEnv WEZTERM_*' >> /etc/ssh/sshd_config.d/wezterm.conf"
sudo sh -c "echo 'AcceptEnv TERM*' >> /etc/ssh/sshd_config.d/wezterm.conf"
sudo sh -c "echo 'AcceptEnv COLORTERM' >> /etc/ssh/sshd_config.d/wezterm.conf"
sudo ssh-keygen -A

# broot
/home/linuxbrew/.linuxbrew/bin/broot --install fish

# wezterm
sudo ln -s /home/linuxbrew/.linuxbrew/bin/wezterm /usr/local/bin/wezterm
