#!/usr/bin/env bash
set -euxo pipefail

# Rye (Python)
curl -sSf https://rye-up.com/get | RYE_INSTALL_OPTION="--yes" bash

# Rust
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --no-modify-path

# mise
curl https://mise.run | bash

# SSH server
sudo apt-get -y install openssh-server
sudo ssh-keygen -A
sudo mkdir -p /etc/ssh/sshd_config.d
echo 'StreamLocalBindUnlink yes' | sudo tee -a /etc/ssh/sshd_config.d/clipper.conf
sudo tee -a /etc/ssh/sshd_config.d/wezterm.conf <<EOF
AcceptEnv WEZTERM*
AcceptEnv TERM*
AcceptEnv COLORTERM
EOF

# wezterm
sudo ln -s /home/linuxbrew/.linuxbrew/bin/wezterm /usr/local/bin/wezterm
