#!/usr/bin/env bash
set -euxo pipefail

git clone https://github.com/pyenv/pyenv.git "$HOME/.pyenv"
git clone https://github.com/pyenv/pyenv-virtualenv.git "$HOME/.pyenv/plugins/pyenv-virtualenv"

export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

# https://github.com/pyenv/pyenv/wiki#suggested-build-environment
sudo apt-get -y install make build-essential libssl-dev zlib1g-dev \
libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm \
libncursesw5-dev xz-utils tk-dev libxml2-dev libxmlsec1-dev libffi-dev liblzma-dev

PYTHON_VERSION=$(pyenv install -l | grep '^ *3.[0-9]*.[0-9]*$' | sort --version-sort | tail -n 1 | sed 's/ *//')
pyenv install "$PYTHON_VERSION"

curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | "$PYENV_ROOT/versions/$PYTHON_VERSION/bin"/python - --no-modify-path
mkdir -p "$XDG_CONFIG_HOME/fish"/completions
"$HOME/.poetry/bin"/poetry completions fish > "$XDG_CONFIG_HOME/fish/completions"/poetry.fish
