#!/bin/bash
set -euxo pipefail

export DOTFILES_HOME="$HOME/.dotfiles"
echo "$DOTFILES_HOME" >"$HOME/.envdotfiles"
git clone https://github.com/ho-oto/dotfiles-for-wsl2 "$DOTFILES_HOME"

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.share"

cd "$DOTFILES_HOME/script"

./apt
./cuda

./cargo
./pyenv
./fzf

./dot

./fisher
./tmux
./julia
./misc

cd "$DOTFILES_HOME"
git checkout .

cat <<EOF
You have to do the following:
1. run tmux and press ^q + I to fetch plugins
2. install python via pyenv and install jupyter lab
3. edit /etc/ssh/sshd_config to disable password
4. copy files in DOTFILES_HOME/windows to /mnt/c/Users/{windows user name}
5. set start_wsl_sshd.bat to Task Scheduler of windows
    
TODO: write bash/PowerShell script to do 3, 5
EOF
