#!/usr/bin/env bash
set -euxo pipefail

command -v wslsys && {
    wslsys | grep WSL2 || {
        echo "This script is made for Ubuntu on WSL2. However, you seem to be using WSL1.";
        echo "Press enter to continue anyway.";
        read -r;
    };
}

export DOTFILES_ROOT="$HOME/.dotfiles"
git clone https://github.com/ho-oto/dotfiles-for-wsl2 "$DOTFILES_ROOT"
cd "$DOTFILES_ROOT/script"

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"

installer/apt
installer/brew
installer/cuda
installer/julia
installer/texlive

installer/cargo
installer/pyenv

./dot

installer/fisher
installer/tmux
installer/misc

cd "$DOTFILES_ROOT"
git checkout .

cat <<EOF
You have to do the following:
1. run tmux and press prefix + I to fetch plugins
2. copy files in DOTFILES_ROOT/windows to /mnt/c/Users/{windows user name}
3. set start_wsl_sshd.bat to Task Scheduler of windows
    
TODO: write bash/PowerShell script to do 2-3
EOF
