#!/usr/bin/bash

sed 's/#.*//' "$DOTFILES_HOME/list/repository" | sed '/^$/d' | xargs sudo add-apt-repository
sudo apt -y update
sudo apt -y upgrade
sed 's/#.*//' "$DOTFILES_HOME/list/apt" | sed '/^$/d' | xargs sudo apt -y install
