#!/usr/bin/bash
set -euxo pipefail

export DOTFILES_HOME="$HOME/.dotfiles"
echo "$DOTFILES_HOME" >"$HOME/.envdotfiles"
git clone https://github.com/ho-oto/dotfiles-for-wsl2 "$DOTFILES_HOME"

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.share"

cd "$DOTFILES_HOME"

./apt
./cuda
./dot
./cargo
./fisher
./tmux
./pyenv
