#!/bin/bash

sed -e 's/#.*//' -e 's/ *//' -e '/^$/d' "$DOTFILES_HOME/list/repository" | while IFS= read -r REPOSITORY
do
    sudo add-apt-repository -y "$REPOSITORY"
done

sudo apt -y update
sudo apt -y upgrade
sed 's/#.*//' "$DOTFILES_HOME/list/apt" | xargs sudo apt -y install
