#!/bin/bash
set -euxo pipefail

REPOSITORIES=(
    ppa:lazygit-team/release
    ppa:fish-shell/release-3
)

PACKAGES=(
    # ssh
    openssh-server
    net-tools
    # build tools
    build-essential
    pkg-config
    m4
    cmake
    gfortran
    # tools
    fish
    ncdu
    htop
    lazygit
    emacs-nox
    unzip
    shellcheck
    jq
    # libs
    libssl-dev
    zlib1g-dev
    libffi-dev
    libreadline-dev
    libsqlite3-dev
    libbz2-dev
)

printf '%s\n' "${REPOSITORIES[@]}" | xargs -L 1 sudo add-apt-repository -y
sudo apt-get -y update
sudo apt-get -y upgrade
echo "${PACKAGES[@]}" | xargs sudo apt-get -y install
