#!/bin/bash
set -euxo

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

formulas=(
    bat
    dust
    exa
    fd
    git-delta
    hyperfine
    procs
    ripgrep
    starship
    tealdeer
    tmux
    tokei
    zoxide
)

brew update

for formula in "${formulas[@]}"; do
    if ! brew list --versions "$formula"; then
        brew install "$formula"
    fi
done
