#!/bin/bash
set -euxo

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

taps=(
    wez/wezterm-linuxbrew
)

formulas=(
    bat
    bottom
    broot
    dust
    exa
    fd
    fzf
    git-delta
    hyperfine
    lazygit
    procs
    pueue
    rclone
    ripgrep
    starship
    tealdeer
    tmux
    tokei
    wezterm
    zoxide
)

for tap in "${taps[@]}"; do
    brew tap "$tap"
done

brew update

for formula in "${formulas[@]}"; do
    if ! brew list --versions "$formula"; then
        brew install "$formula"
    fi
done
