#!/bin/bash
set -euxo pipefail

curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --no-modify-path
sed 's/#.*//' "$DOTFILES_ROOT/list/cargo" | xargs "$HOME/.cargo/bin"/cargo install
