#!/bin/bash
set -euxo pipefail

PACKAGES=(
    bottom
    broot
    cargo-update
    # evcxr_jupyter
    # evcxr_repl
)

curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --no-modify-path
# "$HOME/.cargo/bin"/rustup component add rust-src
echo "${PACKAGES[@]}" | xargs "$HOME/.cargo/bin"/cargo install
