#!/bin/bash
set -euxo pipefail

sudo mkdir -p /etc/ssh/sshd_config.d
sudo sh -c "echo 'StreamLocalBindUnlink yes' >> /etc/ssh/sshd_config.d/clipper.conf"

"$HOME/.cargo/bin"/broot --install fish
# "$HOME/.cargo/bin"/evcxr_jupyter --install
